version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/ruby:2.6.6
    steps:
      - checkout
      - run: echo "this is the test job"
      - when:
          condition: $CIRCLE_PULL_REQUEST
          steps:
            - run: echo "echo it works !!!!"


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
      # - hold:
      #     type: approval
      # - build:
      #     requires:
      #       - hold
      # - test:
      #     requires:
      #       - hold